# Permalinks
permalink:           pretty

# Setup
title:               Tristan's Blog
tagline:             The blog for the best Tristan you know
url:                 http://www.tristansokol.com
paginate:            5
baseurl:             ""

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
# author:
#   name:              Tristan Sokol
#   url:               https://twitter.com/tristansokol
#   email:             tristan.sokol@gmail.com

excerpt_separator: <!--more-->

# Custom vars
github:
  repo:
thanks-to:              https://github.com/poole/poole

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
