# Permalinks
permalink:           pretty

# Setup
title:               Tristan's Blog
tagline:             If only I had a nickel for everytime I made one of these
url:                 http://www.tristansokol.com
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tristan Sokol
  url:               https://twitter.com/tristansokol
  email:             tristan.sokol@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:
thanks-to:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
